#ifndef AMTBDA_H
#define AMTBDA_H

// BDA Tuner Extensions
DEFINE_GUIDSTRUCT("1BFB70F7-ADFB-4414-9FD4-60E9E540A559", KSPROPSETID_BdaDeviceControlProperties);
#define KSPROPSETID_BdaDeviceControlProperties DEFINE_GUIDNAMED(KSPROPSETID_BdaDeviceControlProperties)

typedef enum {
	KSPROPERTY_BDA_IRCODE_PROPERTY = 0,
	KSPROPERTY_BDA_USB_MODE_PROPERTY,
	KSPROPERTY_BDA_ENABLE_PID_PROPERTY,
	KSPROPERTY_BDA_DISABLE_PID_PROPERTY,
	KSPROPERTY_BDA_DEVICE_SUSPEND_STATUS_PROPERTY,
	KSPROPERTY_BDA_PID_FILTER_STATUS_PROPERTY,
	KSPROPERTY_BDA_HIERARCHICAL_MODE_PROPERTY,
    KSPROPERTY_BDA_MT2060CALIBRATION_PROPERTY   	
} KSPROPERTY_BDA_DEVICE_CONTROL;

DEFINE_GUIDSTRUCT("BB992B31-931D-41B1-85EA-A01B4E306CA5", KSPROPSETID_AMDVB_Ctl);
#define KSPROPSETID_AMDVB_Ctl DEFINE_GUIDNAMED(KSPROPSETID_AMDVB_Ctl)

DEFINE_GUIDSTRUCT("F25C6BC9-DBD7-4A0C-B228-9A58789F2E1D", KSPROPSETID_AMDVB_Ter);
#define KSPROPSETID_AMDVB_Ter DEFINE_GUIDNAMED(KSPROPSETID_AMDVB_Ter)

#define KSPROPERTY_AMDVB_DELSYS 3
#define KSPROPERTY_AMDVB_PLPINFO 13
#define KSPROPERTY_AMDVB_TERMODE 14

enum AMDVB_RECEIVER_MODE
{
	RM_DVB_C = 0,	
	RM_DVB_T,
	RM_DVB_T2,
	RM_FMDAB
};

typedef struct _PLPINFO
{
	BYTE current_PLP_ID;
	BYTE current_PLP_No;
	BYTE num_plps;
	BYTE num_data_Plps;
	BYTE id;
	BYTE group_id;
	BYTE type;
	BYTE modulation;
	BYTE coderate;
	BYTE fftmode;
	BYTE reserve1;
	BYTE reserve2;
}PLP_Info;
#endif AMT_H

